### ISSUE TITLE
dusk failed running test ubuntu 14.04

### ISSUE THREAD

**Issue by otim22** [laravel/dusk#165]
PHPUnit 5.7.14 by Sebastian Bergmann and contributors.

EEEPHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
Stack trace:
#0 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('Illuminate\\Cont...')
#3 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(155): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce in /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 804
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
Stack trace:
#0 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('Illuminate\\Cont...')
#3 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(155): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExce in /home/vagrant/Code/mobis4/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 804

**Comment by deleugpn** [comment]
Not a lot of information here to help you.

**Comment by tripper54** [comment]
I have intermittent failures of Dusk tests on CircleCI using an Ubuntu 14.04 build container, with a similar error message (I found this by googling).
Re-running the build _usually_ fixes it. Failure rates are at about 20%, and the error message gives no indication of what specifically went wrong, which is frustrating.

**Comment by tripper54** [comment]
See also https://github.com/laravel/framework/issues/10808
